[package]
name = "scc"
description = "A collection of building blocks for concurrent programming."
version = "0.5.6"
authors = ["wvwwvwwv <wvwwvwwv@me.com>"]
edition = "2018"
readme = "README.md"
repository = "https://github.com/wvwwvwwv/scalable-concurrent-containers/"
license = "Apache-2.0"
categories = ["concurrency", "data-structures"]
keywords = ["concurrent", "ebr", "hashmap", "map", "tree"]

[dependencies]
scopeguard = "^1.1.0"

[dev-dependencies]
criterion = "^0.3.5"
loom = { git = "https://github.com/tokio-rs/loom" }
proptest = "^1.0.0"

[[bench]]
name = "ebr"
harness = false
