[package]
name = "scc"
version = "0.2.0"
authors = ["Changgyoo Park <wvwwvwwv@me.com>"]
edition = "2018"

[dependencies]
crossbeam-epoch="^0.9"
libc="^0.2.80"


[workspace]
members = [
    ".",
    "tests"
]