[package]
name = "scc"
description = "High performance concurrent containers and utilities"
version = "0.6.9"
authors = ["wvwwvwwv <wvwwvwwv@me.com>"]
edition = "2021"
readme = "README.md"
repository = "https://github.com/wvwwvwwv/scalable-concurrent-containers/"
license = "Apache-2.0"
categories = ["concurrency", "data-structures"]
keywords = ["concurrent", "asynchronous", "ebr", "hashmap", "tree"]

[dependencies]
scopeguard = "^1.1"

[dev-dependencies]
criterion = "^0.3"
futures = "^0.3"
loom = "^0.5"
proptest = "^1.0"
tokio = { version = "^1.17.0", features = ["full"] }

[[bench]]
name = "ebr"
harness = false

[[bench]]
name = "hash_map"
harness = false

[[bench]]
name = "hash_index"
harness = false

[[bench]]
name = "tree_index"
harness = false
