[package]
name = "scc"
version = "0.2.2"
authors = ["Changgyoo Park <wvwwvwwv@me.com>", "Changgyoo Park <changgyoo.park@sap.com>"]
edition = "2018"
readme = "README.md"
repository = "https://github.com/wvwwvwwv/scc/"
license = "MIT"
keywords = ["hashmap", "hashtable"]
categories = ["concurrency", "data-structures"]
description = "scalable concurrent data structures for database management systems"

[dependencies]
crossbeam-epoch="^0.9"
libc="^0.2.80"

[workspace]
members = [
    ".",
    "tests"
]