[package]
name = "scc"
description = "Scalable concurrent data structures for database management systems"
version = "0.5.1"
authors = ["wvwwvwwv <wvwwvwwv@me.com>"]
edition = "2018"
readme = "README.md"
repository = "https://github.com/wvwwvwwv/scalable-concurrent-containers/"
license = "Apache-2.0"
categories = ["concurrency", "data-structures"]
keywords = ["concurrent", "hashmap", "map", "tree", "ebr"]

[dependencies]
scopeguard = "^1.1.0"

[dev-dependencies]
criterion = "^0.3.5"
loom = "^0.5.1"
proptest = "^1.0.0"

[[bench]]
name = "ebr"
harness = false