[package]
name = "scc"
description = "Scalable concurrent data structures for database management systems"
version = "0.4.9"
authors = ["wvwwvwwv <wvwwvwwv@me.com>"]
edition = "2018"
readme = "README.md"
repository = "https://github.com/wvwwvwwv/scalable-concurrent-containers/"
license = "Apache-2.0"
categories = ["concurrency", "data-structures"]
keywords = ["concurrent", "hashmap", "map", "tree", "index"]

[dependencies]
crossbeam-epoch = "^0.9.3"
scopeguard = "^1.1.0"

[workspace]
members = [
    ".",
    "tests"
]