name: SCC

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Debug - Build
        run: cargo build --verbose
      - name: Debug -Run unit tests
        run: cargo test --verbose
      - name: Debug - Run tests
        run: cargo test -p tests -- --nocapture
      - name: Release - Build
        run: cargo build --release --verbose
      - name: Release - Run unit tests
        run: cargo test --release --verbose
      - name: Release - Run tests
        run: cargo test --release -p tests -- --nocapture
#      - name: Debug/Segregated - Run tests
#        run: cargo test -p tests -- --test-threads=1 --ignored
#        Rust panic handler allocates!
