name: SCC

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v2
      - name: Debug - Test
        run: RUST_BACKTRACE=1 cargo test --verbose -- --nocapture
      - name: Release - Test
        run: RUST_BACKTRACE=1 cargo test --release --verbose -- --nocapture
      - name: Release - Benchmark
        run: cargo bench
      - name: Debug(serde) - Test
        run: RUST_BACKTRACE=1 cargo test serde --verbose --features serde
      - name: Document - Generate documentation
        run: cargo doc
