name: SCC

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  check-basic:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3
      - name: Debug
        run: RUST_BACKTRACE=1 cargo test --verbose -- --nocapture
      - name: Release
        run: RUST_BACKTRACE=1 cargo test --release --verbose -- --nocapture
  check-extended:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3
      - name: Prepare
        run:
          rustup toolchain add nightly;
          rustup component add rust-src --toolchain nightly;
          rustup component add miri --toolchain nightly
      - name: Lint
        run:
          cargo clippy --all;
          cargo +nightly clippy --all
      - name: Format
        run:
          cargo fmt --all;
          cargo +nightly fmt --all
      - name: Doc
        run:
          cargo doc --document-private-items;
          cargo +nightly doc --document-private-items
      - name: Serde
        run:
          cargo test serde --verbose --features serde;
          cargo +nightly test serde --verbose --features serde
          cargo test --release serde --verbose --features serde;
          cargo +nightly test --release serde --verbose --features serde;
      - name: Miri
        run: cargo +nightly miri test --lib --bins --tests
      - name: Nightly
        run: cargo +nightly test --release benchmark
  benchmark:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3
      - name: Benchmark
        run: cargo bench
